baseURL = "https://onebite.dev"
languageCode = "en-us"
title = "Onebite Dev"
paginate = 15

[params]
    description = "Developer tips and trick one bite at a time"

[permalinks]
  posts = ":slug"

[taxonomies]
    tag = "topic"

[outputs]
    section = ["HTML", "RSS", "JSON"]