baseURL = "https://onebite.dev"
languageCode = "en-us"
title = "Onebite Dev"

[params]
    description = "Developer tips and trick one bite at a time"

[permalinks]
  posts = ":slug"

[taxonomies]
    tag = "topic"